user-data-dir: /Users/pickle/Library/Application Support/Google/Chrome/
url:
  login: https://www.dcu-online.org/tob/live/usp-core/app/login/consumer
  mfa: https://www.dcu-online.org/tob/live/usp-core/app/mfa
  home: https://www.dcu-online.org/tob/live/usp-core/app/home
cc:
  member-number: 5740838
  password: fN0-2xs-2FT-FeT
  mfa-email: dcu@dcu.org
email: 
  address: aadilislam101@gmail.com
  password: Ziqgy0-fozzaj-wefpis
from-account: Free Checking 2
pool-account: Primary Savings 1
to-account: DCU Visa 141
from-account-keep: 300.00